abstract:     VMware's Lab Manager public and private API
installdirs:  site
license:      perl
name:         Term-Activity
version:      VERSIONTAG
version_from: lib/Term/Activity.pm

requires:
  Term::Size: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
